repos:
    - repo: https://github.com/PyCQA/flake8
      rev: 6.0.0
      hooks:
        - id: flake8
          exclude: ds/migrations
    - repo: https://github.com/psf/black
      rev: 22.12.0
      hooks:
        - id: black
          exclude: ds/migrations
    - repo: https://github.com/PyCQA/isort
      rev: 5.10.1
      hooks:
        - id: isort
          exclude: ds/migrations
    - repo: https://github.com/PyCQA/pydocstyle/
      rev: 6.1.1
      hooks:
        - id: pydocstyle
          exclude: tests
