version: "3.9"

services:
    db:
        image: mariadb
        restart: always
        volumes:
            - ./data/db:/var/lib/mysql
        env_file:
            - .env
        ports:
            - 3306:3306
        healthcheck:
            test: "/usr/bin/mysql --user=$MYSQL_USER --password=$MYSQL_PASSWORD --execute \"SHOW DATABASES;\""
            interval: 3s
            timeout: 1s
            retries: 5
        security_opt:
          - label=type:container_runtime_t

    daylio-stats:
        build: .
        volumes:
            - .:/usr/src/app
        ports:
            - 8000:8000
        env_file:
            - .env
        security_opt:
          - label=type:container_runtime_t
        depends_on:
            db:
                condition: service_healthy
